### ISSUE TITLE
Improve tags

### ISSUE THREAD

**Issue by steveoh** [agrc/agol-validator#21]
![image](https://user-images.githubusercontent.com/325813/86977141-2f5ad500-c139-11ea-9909-1596cd42a28c.png)

I don't think the name should be in the tags but paths should be. I did a search for trails and paths agrc and it showed something from wfrc

**Comment by jacobdadams** [comment]
It should be catching tags that are in the title. I'll look at the code; it may be hanging up because it's an exact match with the title. `Paths` being included in the tags is a dataset-specific issue that's probably best tackled in the Porter issue.

**Comment by steveoh** [comment]
So the tags that get applied to agol come from the sgid metadata?

**Comment by jacobdadams** [comment]
Yes, in part, assuming the SDE metadata is properly set up. 

I believe the initial publish procedure tries to populate the AGOL summary, description, use constraints, credits, and tags from the SDE metadata. 

Then, when agol-validator is run it creates an arcpy metadata object from the feature class and pulls over anything in its `.tags` property (so that if tags in the SDE metadata are updated they are propagated to AGOL). It will also keep any additional tags that have been added to AGOL (it gets the list of existing AGOL tags, appends the tags from SDE metadata, and then evaluates each one to see if it should be kept).

**Comment by steveoh** [comment]
I"ll let you close this when the title isn't in the tags :)

**Comment by jacobdadams** [comment]
Ok, looking at the logs, agol-validator didn't add the `Utah Trails and Pathways` tag. It probably came over when I manually uploaded the metadata for this AGOL item.

However, now that I think about it, the fact that updating the AGOL metadata pulls any tags from the SDE metadata creates a problem where the validator updates the tags from existing AGOL and metadata tags (and properly removes any that are in the title) and then the tags get promptly overwritten by the metadata fix. I think I need to move the tag fix to occur after the metadata fix.

**Comment by jacobdadams** [comment]
Hey, look at that, the tags fix is already after the metadata fix (as are the title and description fixes). Guess I figured that out before and then forgot it. I'll add a note for posterity in the code in the next commit about this.

(And I just confirmed, `Utah Trails and Pathways` is in the SDE metadata for the feature class, so that's most likely where it came from)

**Comment by steveoh** [comment]
So the validator should remove this tag then since it is a duplicate? I've asked @gregbunce to remove it from SDE.

**Comment by jacobdadams** [comment]
Yeah, it should next time it runs. I've tested the logic (outside of the program, because I don't have tests written for agol-validator) and it should catch it and remove it.

**Comment by jacobdadams** [comment]
I'll look through the logs to see if there's anything else with the title
in the tags—it should be catching that and reporting it, even if it's
getting overwritten.

**Comment by gregbunce** [comment]
i cleaned up the tags in Internal SDE.  they now follow our guidelines.

**Comment by jacobdadams** [comment]
> since greg updated sde i don't think it will be a good test. we might want to look for others with the same issue. Are you thinking that the validator hadn't been run since trails and pathways was added? Or why wasn't it fixed by the validator already?

It wasn't fixed because I had to manually force the metadata update Tuesday because it was too large so we had to trim it first, and agol-validator hasn't run since then.

I just dumped all the SDE metadata tags out to csv, and it looks like the only possible match is `Utah State Courts` for 'SGID.SOCIETY.StateCourtDistricts' (http://utah.maps.arcgis.com/home/item.html?id=2938c95d71444c5cb527a2fda25629d9). This tag hasn't been removed because `Utah State Courts` is not in `Utah State Court Districts`

**Comment by steveoh** [comment]
Ok, maybe we should simulate the error with a less popular dataset or with a test with modified xml to be sure

**Comment by jacobdadams** [comment]
Yeah, I've got an AGOL item and faux metatable in my own folders I'm using for testing. I can go back and add a tag to an feature class' SDE metadata and point my item at it to check.

**Comment by jacobdadams** [comment]
It's working as expected:
![image](https://user-images.githubusercontent.com/38168030/87092481-bd49c500-c1f8-11ea-8a6c-7425f064522b.png)
![image](https://user-images.githubusercontent.com/38168030/87092545-da7e9380-c1f8-11ea-95eb-30fe688cb29c.png)
(and "Foo" was a pre-existing tag)

**Comment by steveoh** [comment]
Awesome, I'd love to see these tests added to the repository!

**Comment by jacobdadams** [comment]
TBH, test frameworks are a little outside my wheelhouse right now. This is just from manually running it against the fake metatable (http://utah.maps.arcgis.com/home/item.html?id=e5380e8b57924192a8e39cfe8c6f5a0a) and test item (http://utah.maps.arcgis.com/home/item.html?id=d2ea8eb22aa64d22800bc370bb1b128b) in my AGOL folders, updating the metatable entry for that test item as needed. I'm realizing that my engineering is very tightly coupled, thus making it difficult to test individual components.

**Comment by steveoh** [comment]
well, i'm happy to help expand your wheelhouse. whenever you would like to schedule some time let me know.
